name: news_app
description: News from NewsAPI
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cached_network_image: ^2.2.0+1
  webview_flutter: ^0.3.22+1
  google_fonts: ^1.1.0
  chopper: ^3.0.3
  built_value: ^7.1.0
  built_collection: ^4.3.2
  url_launcher: ^5.5.0
  moor_flutter: ^3.1.0
  get_it: ^4.0.4
  provider: ^4.3.2
  progress_indicators: ^0.1.5
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  build_runner: ^1.10.0
  chopper_generator: ^3.0.5
  built_value_generator: ^7.1.0
  moor_generator: ^3.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon.png"
  adaptive_icon_foreground: "assets/appIcon-adaptive.png"
  adaptive_icon_background: "#FF5E5B"

flutter:
  uses-material-design: true
  assets:
    - assets/
